name = "testPkg"
uuid = "28992b39-f826-4ca1-979d-6add1110b67b"
authors = ["Terry Seaward", "IAM"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
